name: Build Arch ISO

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Maximize Build Space
        run: |
          # مسح الملفات الضخمة لتوفير مساحة (تصل لـ 30 جيجا)
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /usr/lib/jvm /usr/local/share/boost
          sudo apt-get clean
          df -h

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build ISO
        run: |
          mkdir -p out
          chmod 777 out

          docker run --rm --privileged \
            -v ${{ github.workspace }}:/repo \
            archlinux:latest \
            /bin/bash -c "
              # 1. تحديث النظام بالكامل قبل أي شيء
              pacman -Syu --noconfirm && \

              # 2. تحديث المفاتيح الأساسية
              pacman -Sy --noconfirm archlinux-keyring && \

              # 3. تثبيت أدوات البناء والـreflector
              pacman -S --noconfirm archiso git reflector && \

              # 4. تحديث قائمة الـmirrors لتفادي ملفات تالفة
              reflector --latest 10 --sort rate --save /etc/pacman.d/mirrorlist && \

              # 5. مسح الكاش للتأكد إن مفيش ملفات تالفة
              pacman -Scc --noconfirm && \

              # 6. تعديل pacman.conf حسب الحاجة
              sed -i 's/SigLevel    = Required DatabaseOptional/SigLevel = Optional TrustAll/g' /repo/pacman.conf && \

              # 7. حذف الحزم الغير موجودة
              sed -i '/^cheese$/d' /repo/packages.x86_64 && \

              # 8. تشغيل البناء
              mkarchiso -v -w /tmp/archiso-work -o /repo/out /repo
            "

      - name: Upload ISO
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: arch-iso
          path: out/*.iso
